# Generated by Django 4.0.3 on 2022-04-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Boardx',
        ),
    ]
